apiVersion: v1
kind: Secret
metadata:
  name: chatbot-app-secret
type: Opaque
stringData:
  database_url: postgresql://chatbot:chatbot@chatbot-postgres:5432/chatbot?schema=public
  llm_api_key: your_api_key_here
